FIX: Change handlePayment to handleConfirmPayment - fixes property detail page crash
ReferenceError: handlePayment is not defined
- Function was named handleConfirmPayment but button called handlePayment
- This caused the page to crash when clicking Pay button